language: csharp
script:
  - xbuild /p:Configuration=Release SelfHostWindowsAuthentication.sln
  - xbuild /p:Configuration=Release IdentityAdminWindowsAuthentication.sln  
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./SelfHostWindowsAuthentication.sln
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./IdentityAdminWindowsAuthentication.sln
